### ISSUE TITLE
Failing to create a new profile

### ISSUE THREAD

**Issue by kyrylo** [bil-bas/ruby_armor#2]
The revision, which I'm working with:
commit 0ce1fa4e9407a01bb5dcc87b6c9a4d009150fc41
Author: Bil Bas (Spooner) bil.bagpuss@gmail.com
Date:   Sun Mar 4 01:58:38 2012 +0000

```
Added tool-tips for parts of the dungeon (you, enemies, walls, stairs, etc).
```

The description:
I've deleted previously cloned repository and the save games. Then I've cloned your repository second time and now I can't launch the game (the first go was ok).

The backtrace:
    `% ruby bin/ruby_armor.rbw 
/home/curacao/ruby_armor/lib/ruby_armor/states/create_profile.rb:27:in `block (3 levels) in initialize': uninitialized constant RubyArmor::Play::WARRIORS (NameError)
    from /usr/lib/ruby/gems/1.9.1/gems/fidgit-0.2.4/lib/fidgit/redirector.rb:14:in `instance_methods_eval'
    from /usr/lib/ruby/gems/1.9.1/gems/fidgit-0.2.4/lib/fidgit/elements/element.rb:281:in `with'
    from /usr/lib/ruby/gems/1.9.1/gems/fidgit-0.2.4/lib/fidgit/elements/container.rb:183:in `post_init_block'
    from /usr/lib/ruby/gems/1.9.1/gems/fidgit-0.2.4/lib/fidgit/elements/element.rb:96:in `new'
    from /usr/lib/ruby/gems/1.9.1/gems/fidgit-0.2.4/lib/fidgit/elements/container.rb:100:in `horizontal'
    from /usr/lib/ruby/gems/1.9.1/gems/fidgit-0.2.4/lib/fidgit/redirector.rb:44:in `block (2 levels) in push_redirection_target'
    from /home/curacao/ruby_armor/lib/ruby_armor/states/create_profile.rb:26:in `block (2 levels) in initialize'
    from /usr/lib/ruby/gems/1.9.1/gems/fidgit-0.2.4/lib/fidgit/redirector.rb:14:in `instance_methods_eval'
    from /usr/lib/ruby/gems/1.9.1/gems/fidgit-0.2.4/lib/fidgit/elements/element.rb:281:in `with'
    from /usr/lib/ruby/gems/1.9.1/gems/fidgit-0.2.4/lib/fidgit/elements/container.rb:183:in `post_init_block'
    from /usr/lib/ruby/gems/1.9.1/gems/fidgit-0.2.4/lib/fidgit/elements/element.rb:96:in `new'
    from /usr/lib/ruby/gems/1.9.1/gems/fidgit-0.2.4/lib/fidgit/elements/container.rb:80:in `group'
    from /usr/lib/ruby/gems/1.9.1/gems/fidgit-0.2.4/lib/fidgit/redirector.rb:44:in `block (2 levels) in push_redirection_target'
    from /home/curacao/ruby_armor/lib/ruby_armor/states/create_profile.rb:25:in `block in initialize'
    from /usr/lib/ruby/gems/1.9.1/gems/fidgit-0.2.4/lib/fidgit/redirector.rb:14:in `instance_methods_eval'
    from /usr/lib/ruby/gems/1.9.1/gems/fidgit-0.2.4/lib/fidgit/elements/element.rb:281:in `with'
    from /usr/lib/ruby/gems/1.9.1/gems/fidgit-0.2.4/lib/fidgit/elements/container.rb:183:in `post_init_block'
    from /usr/lib/ruby/gems/1.9.1/gems/fidgit-0.2.4/lib/fidgit/elements/element.rb:96:in `new'
    from /usr/lib/ruby/gems/1.9.1/gems/fidgit-0.2.4/lib/fidgit/elements/container.rb:106:in `vertical'
    from /home/curacao/ruby_armor/lib/ruby_armor/states/create_profile.rb:16:in `initialize'
    from /home/curacao/ruby_armor/lib/ruby_armor/states/choose_profile.rb:41:in `new'
    from /home/curacao/ruby_armor/lib/ruby_armor/states/choose_profile.rb:41:in `block (3 levels) in setup'
    from /usr/lib/ruby/gems/1.9.1/gems/fidgit-0.2.4/lib/fidgit/event.rb:128:in `call'
    from /usr/lib/ruby/gems/1.9.1/gems/fidgit-0.2.4/lib/fidgit/event.rb:128:in `block in publish'
    from /usr/lib/ruby/gems/1.9.1/gems/fidgit-0.2.4/lib/fidgit/event.rb:127:in `reverse_each'
    from /usr/lib/ruby/gems/1.9.1/gems/fidgit-0.2.4/lib/fidgit/event.rb:127:in `publish'
    from /usr/lib/ruby/gems/1.9.1/gems/fidgit-0.2.4/lib/fidgit/states/gui_state.rb:283:in `redirect_released_mouse_button'
    from /usr/lib/ruby/gems/1.9.1/gems/fidgit-0.2.4/lib/fidgit/states/gui_state.rb:73:in `block in initialize'
    from /usr/lib/ruby/gems/1.9.1/gems/chingu-0.9rc7/lib/chingu/helpers/input_dispatcher.rb:83:in `[]'
    from /usr/lib/ruby/gems/1.9.1/gems/chingu-0.9rc7/lib/chingu/helpers/input_dispatcher.rb:83:in `block in dispatch_actions'
    from /usr/lib/ruby/gems/1.9.1/gems/chingu-0.9rc7/lib/chingu/helpers/input_dispatcher.rb:80:in `each'
    from /usr/lib/ruby/gems/1.9.1/gems/chingu-0.9rc7/lib/chingu/helpers/input_dispatcher.rb:80:in `dispatch_actions'
    from /usr/lib/ruby/gems/1.9.1/gems/chingu-0.9rc7/lib/chingu/helpers/input_dispatcher.rb:53:in `dispatch_button_up'
    from /usr/lib/ruby/gems/1.9.1/gems/chingu-0.9rc7/lib/chingu/game_state.rb:163:in `button_up'
    from /usr/lib/ruby/gems/1.9.1/gems/chingu-0.9rc7/lib/chingu/game_state_manager.rb:268:in `button_up'
    from /usr/lib/ruby/gems/1.9.1/gems/chingu-0.9rc7/lib/chingu/window.rb:171:in `button_up'
    from bin/ruby_armor.rbw:7:in `<main>'`

Other notes:
Launching the game with `ruby bin/ruby_armor` works as intended (but it launches the old version instead of the latest).

**Comment by bil-bas** [comment]
Yeah, I found that one when I tried it when you were playing earlier (it is a problem with creating a new profile). I just didn't push it since I haven't sorted out git on Linux yet.
